feat(template): Agrega templates en portugés y agrega alertas en español #4
Laboratoria/tech-support pull request #7
Opened 2022-09-30 17:17 UTC by adolivaresl

2022-10-03 09:14 UTC, adsoncostanzifilho requested changes
:star:

2022-10-03 09:14 UTC, adsoncostanzifilho commented on .github/ISSUE_TEMPLATE/feature_request.pt.md
> +Eu fico frustrado quando [...]
Sustituir:
Por exemplo, eu sempre Eu fico frustrado quando [...] -> Por exemplo, eu fico frustrada quando [...]

2022-10-04 18:40 UTC, adolivaresl commented on .github/ISSUE_TEMPLATE/feature_request.pt.md
> +Eu fico frustrado quando [...]
gracias @adsoncostanzifilho ! agregaré tu corrección :)

2022-10-18 09:38 UTC, lupomontero approved these changes
LGTM :star:

2022-10-18 09:40 UTC, merged